
funcList = [
    "addExtensions",
    #----- triggers --------
    "triger_created_updated",
    "triger_notify_event",
    "trigger_user_fullname_update",
    "trigger_task_update_table_name",
    "trigger_task_type_change",
    "trigger_chat_update_table_name",
    #----- util --------
    "small_funcs",
    "build_query_part_for_list",
    "check_required_params",
    "update_str_from_json",
    "where_str_build",
]
